# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Mode自动解析' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!



    pod 'MJExtension', '~> 3.0.13'
  # Pods for Mode自动解析

end
